package com.reqshift.output;

import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import com.reqshift.core.model.AnalysisReport;
import com.reqshift.core.model.Category;
import com.reqshift.core.model.RuleResult;
import com.reqshift.core.model.Severity;
import com.reqshift.core.model.Violation;

public final class HtmlReportFormatter {

    private final String toolVersion;

    public HtmlReportFormatter() {
        this("dev");
    }

    public HtmlReportFormatter(String toolVersion) {
        this.toolVersion = toolVersion == null || toolVersion.isBlank() ? "dev" : toolVersion;
    }

    public String format(AnalysisReport report) {
        String generatedAt = OffsetDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);

        StringBuilder sb = new StringBuilder(8192);
        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"en\"><head><meta charset=\"utf-8\">\n");
        sb.append("<title>ReqShift Report — ")
                .append(escape(report.openApiSource()))
                .append("</title>\n");
        sb.append(styles()).append("</head><body>\n");

        sb.append("<header><h1>ReqShift Analysis Report</h1>\n");
        sb.append("<dl class=\"meta\">");
        sb.append("<dt>Source</dt><dd>").append(escape(report.openApiSource())).append("</dd>");
        sb.append("<dt>Generated</dt><dd>").append(escape(generatedAt)).append("</dd>");
        sb.append("<dt>ReqShift</dt><dd>").append(escape(toolVersion)).append("</dd>");
        sb.append("</dl></header>\n");

        sb.append("<section class=\"score\">\n");
        sb.append(scoreGauge(report));
        sb.append(scoreBreakdown(report));
        sb.append("</section>\n");

        sb.append("<section class=\"violations\">\n");
        sb.append("<h2>Violations</h2>\n");
        Map<Category, List<Violation>> byCategory = groupViolations(report);
        if (byCategory.isEmpty()) {
            sb.append("<p class=\"empty\">No violations found.</p>\n");
        } else {
            byCategory.entrySet().stream()
                    .sorted(Map.Entry.comparingByKey())
                    .forEach(e -> sb.append(renderCategory(e.getKey(), e.getValue())));
        }
        sb.append("</section>\n");

        sb.append("<footer>Generated by ReqShift ")
                .append(escape(toolVersion))
                .append("</footer>\n");
        sb.append("</body></html>\n");
        return sb.toString();
    }

    private String scoreGauge(AnalysisReport report) {
        int overall = report.score().overall();
        char grade = report.score().grade();
        String color = colorForGrade(grade);
        int circumference = 339;
        int dash = Math.max(0, Math.min(circumference, overall * circumference / 100));

        StringBuilder sb = new StringBuilder();
        sb.append("<div class=\"gauge\">\n");
        sb.append("<svg viewBox=\"0 0 120 120\" width=\"160\" height=\"160\">\n");
        sb.append(
                "<circle cx=\"60\" cy=\"60\" r=\"54\" fill=\"none\" stroke=\"#eee\" stroke-width=\"10\"/>\n");
        sb.append(
                String.format(
                        "<circle cx=\"60\" cy=\"60\" r=\"54\" fill=\"none\" stroke=\"%s\""
                                + " stroke-width=\"10\" stroke-linecap=\"round\""
                                + " stroke-dasharray=\"%d %d\" transform=\"rotate(-90 60 60)\"/>\n",
                        color, dash, circumference));
        sb.append(
                String.format(
                        "<text x=\"60\" y=\"58\" text-anchor=\"middle\" font-size=\"36\""
                                + " font-weight=\"bold\" fill=\"%s\">%s</text>\n",
                        color, grade));
        sb.append(
                String.format(
                        "<text x=\"60\" y=\"82\" text-anchor=\"middle\" font-size=\"14\""
                                + " fill=\"#666\">%d / 100</text>\n",
                        overall));
        sb.append("</svg>\n");
        if (report.score().isCapped()) {
            sb.append("<p class=\"cap\">Capped from ")
                    .append(report.score().rawOverall())
                    .append(" due to a ")
                    .append(report.score().cappedBy().name())
                    .append(" violation.</p>\n");
        }
        sb.append("</div>\n");
        return sb.toString();
    }

    private String scoreBreakdown(AnalysisReport report) {
        StringBuilder sb = new StringBuilder();
        sb.append("<ul class=\"breakdown\">\n");
        report.score().byCategory().entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .forEach(
                        e ->
                                sb.append("<li><span class=\"cat\">")
                                        .append(escape(e.getKey().name()))
                                        .append("</span><span class=\"val\">")
                                        .append(e.getValue())
                                        .append("</span></li>\n"));
        sb.append("</ul>\n");
        return sb.toString();
    }

    private String renderCategory(Category category, List<Violation> violations) {
        StringBuilder sb = new StringBuilder();
        sb.append("<details open class=\"category\"><summary>")
                .append(escape(category.name()))
                .append(" <span class=\"count\">")
                .append(violations.size())
                .append("</span></summary>\n");
        sb.append("<ul class=\"vlist\">\n");
        violations.stream()
                .sorted(Comparator.comparing((Violation v) -> v.severity().ordinal()).reversed())
                .forEach(v -> sb.append(renderViolation(v)));
        sb.append("</ul></details>\n");
        return sb.toString();
    }

    private String renderViolation(Violation v) {
        StringBuilder sb = new StringBuilder();
        sb.append("<li class=\"violation sev-")
                .append(v.severity().name().toLowerCase())
                .append("\">\n");
        sb.append("<div class=\"head\">");
        sb.append("<span class=\"badge\">").append(v.severity().name()).append("</span>");
        sb.append("<span class=\"rid\">").append(escape(v.ruleId())).append("</span>");
        sb.append("<span class=\"msg\">").append(escape(v.message())).append("</span>");
        sb.append("</div>\n");
        if (v.location() != null && !v.location().isBlank()) {
            sb.append("<div class=\"loc\"><span>Location</span><code>")
                    .append(escape(v.location()))
                    .append("</code></div>\n");
        }
        if (v.suggestion() != null && !v.suggestion().isBlank()) {
            sb.append("<div class=\"sug\"><span>Suggestion</span>")
                    .append(escape(v.suggestion()))
                    .append("</div>\n");
        }
        sb.append("</li>\n");
        return sb.toString();
    }

    private Map<Category, List<Violation>> groupViolations(AnalysisReport report) {
        Map<Category, List<Violation>> byCategory = new EnumMap<>(Category.class);
        for (RuleResult result : report.results()) {
            if (!result.violations().isEmpty()) {
                byCategory
                        .computeIfAbsent(result.rule().category(), k -> new ArrayList<>())
                        .addAll(result.violations());
            }
        }
        return byCategory;
    }

    static String colorForGrade(char grade) {
        return switch (grade) {
            case 'A' -> "#2e7d32";
            case 'B' -> "#689f38";
            case 'C' -> "#fbc02d";
            case 'D' -> "#f57c00";
            default -> "#d32f2f";
        };
    }

    static String colorForSeverity(Severity severity) {
        return switch (severity) {
            case CRITICAL -> "#d32f2f";
            case ERROR -> "#f57c00";
            case WARNING -> "#fbc02d";
            case INFO -> "#1976d2";
        };
    }

    static String escape(String input) {
        if (input == null) {
            return "";
        }
        StringBuilder out = new StringBuilder(input.length());
        for (int i = 0; i < input.length(); i++) {
            char c = input.charAt(i);
            switch (c) {
                case '&' -> out.append("&amp;");
                case '<' -> out.append("&lt;");
                case '>' -> out.append("&gt;");
                case '"' -> out.append("&quot;");
                case '\'' -> out.append("&#39;");
                default -> out.append(c);
            }
        }
        return out.toString();
    }

    private static String styles() {
        return """
                <style>
                  :root { color-scheme: light; }
                  * { box-sizing: border-box; }
                  body { margin: 0; font: 14px/1.5 -apple-system, BlinkMacSystemFont, 'Segoe UI',
                         Roboto, sans-serif; color: #222; background: #fafafa; }
                  header { padding: 32px 48px 16px; background: white; border-bottom: 1px solid #eee; }
                  h1 { margin: 0 0 12px; font-size: 24px; }
                  h2 { font-size: 18px; margin: 0 0 16px; }
                  dl.meta { display: grid; grid-template-columns: max-content 1fr; gap: 4px 16px;
                            margin: 0; font-size: 13px; color: #555; }
                  dl.meta dt { font-weight: 600; }
                  dl.meta dd { margin: 0; font-family: ui-monospace, 'SF Mono', Menlo, monospace; }
                  section { padding: 24px 48px; }
                  section.score { display: flex; gap: 48px; align-items: center; background: white;
                                  border-bottom: 1px solid #eee; }
                  .gauge { display: flex; flex-direction: column; align-items: center; gap: 8px; }
                  .gauge .cap { font-size: 12px; color: #d32f2f; margin: 0; max-width: 200px;
                                text-align: center; }
                  ul.breakdown { list-style: none; padding: 0; margin: 0; flex: 1;
                                 display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px 24px; }
                  ul.breakdown li { display: flex; justify-content: space-between;
                                    padding: 6px 12px; background: #f5f5f5; border-radius: 6px; }
                  ul.breakdown .val { font-family: ui-monospace, monospace; font-weight: 600; }
                  details.category { background: white; border: 1px solid #eee; border-radius: 8px;
                                     margin-bottom: 12px; }
                  details.category summary { padding: 12px 16px; cursor: pointer; font-weight: 600;
                                             display: flex; gap: 12px; align-items: center; }
                  details.category .count { background: #eee; padding: 2px 8px; border-radius: 10px;
                                            font-size: 12px; font-weight: 500; color: #555; }
                  ul.vlist { list-style: none; padding: 0 16px 12px; margin: 0; }
                  li.violation { padding: 12px; border-top: 1px solid #f0f0f0; }
                  li.violation .head { display: flex; gap: 8px; align-items: baseline;
                                       flex-wrap: wrap; }
                  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px;
                           color: white; font-size: 11px; font-weight: 600; letter-spacing: 0.3px; }
                  .sev-critical .badge { background: #d32f2f; }
                  .sev-error    .badge { background: #f57c00; }
                  .sev-warning  .badge { background: #fbc02d; color: #333; }
                  .sev-info     .badge { background: #1976d2; }
                  .rid { font-family: ui-monospace, monospace; font-weight: 600; color: #444; }
                  .msg { flex: 1; min-width: 0; }
                  .loc, .sug { font-size: 13px; color: #555; margin-top: 6px;
                               display: flex; gap: 8px; }
                  .loc span, .sug span { font-weight: 600; min-width: 84px; }
                  .loc code { font-family: ui-monospace, monospace; background: #f5f5f5;
                              padding: 1px 6px; border-radius: 4px; }
                  .empty { color: #2e7d32; font-weight: 600; }
                  footer { padding: 16px 48px 32px; color: #777; font-size: 12px;
                           border-top: 1px solid #eee; background: white; }
                </style>
                """;
    }
}
